### ISSUE TITLE
Remove CyberSource/cybersource-rest-client-php, remove parentheses from auth

### ISSUE THREAD

**Issue by mominsid** [jauntin/cybersource#2]
## Description

Update jauntin/cybersource to be decoupled from `cybersource/cybersource-rest-client-php`, and remove parentheses from the http signature. See equivalent change in https://github.com/CyberSource/cybersource-rest-client-php/pull/136/commits/cca6a4b0966bb1f06920aec96b4a3048c85804d6

![Image](https://github.com/jauntin/infrastructure/assets/74005408/2d561c5d-3286-4db5-9763-c94e537fdc41)

This issue was created in response to https://github.com/jauntin/infrastructure/issues/129

## Acceptance Criteria

- HTTP signature is updated and does not contain parentheses
- Cybersource calls `payment`, `refund`, `generateToken` continue to work in apps

## Tasks

- Build the authentication system
  - Http signatures cannot have parentheses, as noted by cybersource

For each call, `payment`, `refund`, `generateToken`,

- Determine the request and response to apply
- Build the request workflow and map requests and responses to existing types.

## Definition of Ready

- [x] Doesn't have unmet dependencies
- [x] Description is clear and concise
- [x] Acceptance criteria is provided and clear

## Definition of Done

- [ ] PR accepted
- [ ] DEV environment updated
- [ ] QA tests pass (acceptance criteria met, functional and non-functional requirements met, bugs are absent)
- [ ] PO tests pass
- [ ] UAT environment updated
- [ ] QA tests pass
- [ ] Customer tests pass
- [ ] PROD environment updated
- [ ] QA/PO tests pass (if applicable)
